services:
  frontend:
    build:
      context: ./frontend

    # backend host need to be with value 'backend'
    env_file:
      ./frontend/.docker-env

    ports:
       - "3000:3000"

  backend:
    build:
      context: ./backend

    # database host need to be with value 'postgres'
    env_file:
      - ./backend/.docker-env
    
    ports:
      - "1337:1337"

  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: always

    ports:
      - "5432:5432"

    volumes:
      - ~/Desktop/workspace/databases/postgres_data:/var/lib/postgresql/data